/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export type CategoryControllerFindAllParams = {
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
pageSize?: number;
/**
 * Search term for filtering
 */
search?: string;
/**
 * Filter categories by title (case-insensitive partial match)
 */
title?: string;
};
