/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDtoDeletedAt } from './categoryDtoDeletedAt';

export interface CategoryDto {
  /** The unique identifier of the category */
  id: string;
  /** The title of the category */
  title: string;
  /** The ID of the user who owns this category */
  ownerId: string;
  /** Timestamp when the category was created */
  createdAt: string;
  /** Timestamp when the category was last updated */
  updatedAt: string;
  /**
     * Timestamp when the category was soft-deleted
     * @nullable
     */
  deletedAt?: CategoryDtoDeletedAt;
}
