/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export interface CreateCategoryDto {
  /**
     * The title of the category
     * @minLength 3
     * @maxLength 50
     */
  title: string;
}
