/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedResponseDtoDataItem } from './paginatedResponseDtoDataItem';
import type { PaginationMetaDto } from './paginationMetaDto';

export interface PaginatedResponseDto {
  /** Array of items */
  data: PaginatedResponseDtoDataItem[];
  /** Pagination metadata */
  meta: PaginationMetaDto;
}
