/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export interface TaskCategoryDto {
  /** Identificador único da categoria */
  id: string;
  /** Título da categoria */
  title: string;
  /** Identificador do proprietário da categoria */
  ownerId: string;
  /** Data de criação da categoria */
  createdAt: string;
  /** Data de última atualização da categoria */
  updatedAt: string;
}
