/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { TasksControllerFindAllPriority } from './tasksControllerFindAllPriority';
import type { TasksControllerFindAllSortBy } from './tasksControllerFindAllSortBy';
import type { TasksControllerFindAllSortOrder } from './tasksControllerFindAllSortOrder';
import type { TasksControllerFindAllStatus } from './tasksControllerFindAllStatus';

export type TasksControllerFindAllParams = {
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
pageSize?: number;
/**
 * Search term for filtering
 */
search?: string;
/**
 * Filtro por status
 */
status?: TasksControllerFindAllStatus;
/**
 * Filtro por prioridade
 */
priority?: TasksControllerFindAllPriority;
/**
 * Campo de ordenação
 */
sortBy?: TasksControllerFindAllSortBy;
/**
 * Direção da ordenação
 */
sortOrder?: TasksControllerFindAllSortOrder;
};
